### ISSUE TITLE
How to set the SECRET_KEY

### ISSUE THREAD

**Issue by bee1850** [mayflower/authentik-nix#3]
Whenever I'm trying to rebuild my nixOS flake the authentik-migrate.service keeps failing. I get the following error messages: 
- `<module> SIGNING_HASH = sha512(settings.SECRET_KEY.encode()).hexdigest()`
- `__getattr__  raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")`

I tried to set the AUTHENTIK_SECRET_KEY variable in the configuration.nix by adding (keytemp contains the output of `pwgen -s 50 1`) : 
```
  services.authentik = {
    enable = true;
    settings = {
      authentik_secret_key = "${lib.strings.fileContents ./keytemp}";
    };
  };
```
resulting in:
```
cat /etc/authentik/config.yml
authentik_secret_key: 6yrwkZywIBIsqoQ********************SnYdPDGkjQTC***
blueprints_dir: /nix/store/63hrzp6clrdsa7cx3vjlmky1x4fq37pv-authentik-static-workdir-deps/blueprints
postgresql:
  host: ''
  name: authentik
  user: authentik
template_dir: /nix/store/63hrzp6clrdsa7cx3vjlmky1x4fq37pv-authentik-static-workdir-deps/templates
```
Im puzzled on how to proceed and would really appreciate some help.
